"""
SQLAlchemy declarative base, shared by every model in app/db/models/.

Schema reference: documnets/understanding/11_DATA_MODEL_AND_STORAGE.md. That document is a
PROPOSED schema, synthesized from the rest of the understanding/ folder, not a client-mandated
spec -- validate against real application needs before treating a migration as final (see that
doc's own header note).
"""

from sqlalchemy import MetaData
from sqlalchemy.orm import DeclarativeBase

# A fixed naming convention makes Alembic's autogenerated constraint names deterministic and
# diffable across environments -- avoids the classic "autogenerate produces a no-op migration
# with a random constraint rename" problem.
NAMING_CONVENTION = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    metadata = MetaData(naming_convention=NAMING_CONVENTION)
