"""initial schema

Revision ID: 55d2a5a1ec24
Revises: 
Create Date: 2026-09-28 15:24:26.190625

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector.sqlalchemy  # required for the Vector columns below -- autogenerate never adds this
# import on its own (a known pgvector+alembic gap); add it by hand to every future migration
# that touches a Vector column too.

# revision identifiers, used by Alembic.
revision: str = '55d2a5a1ec24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kb_anxiety_situations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('broad_situation', sa.String(), nullable=False),
    sa.Column('subtopics_raw', sa.Text(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_anxiety_situations'))
    )
    op.create_table('kb_career_lookup',
    sa.Column('entry_no', sa.Integer(), nullable=False),
    sa.Column('career_name', sa.String(), nullable=False),
    sa.Column('field_category', sa.String(), nullable=False),
    sa.Column('likely_academic_stream', sa.String(), nullable=False),
    sa.Column('career_name_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.PrimaryKeyConstraint('entry_no', name=op.f('pk_kb_career_lookup'))
    )
    op.create_table('kb_clarification_phrases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('has_drafting_note', sa.Boolean(), nullable=False),
    sa.Column('phrase_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_clarification_phrases'))
    )
    op.create_table('kb_emotion_phrases',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('emotion_label', sa.String(), nullable=False),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('source_list', sa.String(), nullable=False),
    sa.Column('canonical_emotion_group', sa.String(), nullable=True),
    sa.Column('phrase_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_emotion_phrases'))
    )
    op.create_table('kb_fallback_scenarios',
    sa.Column('scenario_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('section', sa.String(), nullable=False),
    sa.Column('disorder_group', sa.String(), nullable=True),
    sa.Column('scenario_type', sa.Text(), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=False),
    sa.Column('fallback_action', sa.Text(), nullable=True),
    sa.Column('bot_script', sa.Text(), nullable=True),
    sa.Column('escalation_path', sa.Text(), nullable=True),
    sa.Column('clinical_reasoning', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.CheckConstraint("section IN ('A_insufficient','B_contradictory','C_disengagement','D_special_population','disorder_matrix')", name=op.f('ck_kb_fallback_scenarios_section_valid')),
    sa.PrimaryKeyConstraint('scenario_id', name=op.f('pk_kb_fallback_scenarios'))
    )
    op.create_table('kb_guardrail_rules',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('concern_category', sa.String(), nullable=False),
    sa.Column('referral_urgency', sa.String(), nullable=False),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_guardrail_rules'))
    )
    op.create_table('kb_layer_content',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('layer', sa.String(), nullable=False),
    sa.Column('section', sa.String(), nullable=True),
    sa.Column('section_type', sa.String(), nullable=False),
    sa.Column('emotion_label', sa.String(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.CheckConstraint("layer IN ('I','II','III','IV')", name=op.f('ck_kb_layer_content_layer_valid')),
    sa.CheckConstraint("section_type IN ('generic','emotion_specific','transition')", name=op.f('ck_kb_layer_content_section_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_layer_content'))
    )
    op.create_table('kb_red_flags',
    sa.Column('flag_id', sa.String(), nullable=False),
    sa.Column('trigger_phrases', sa.ARRAY(sa.Text()), nullable=False),
    sa.Column('trigger_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('clinical_meaning', sa.Text(), nullable=True),
    sa.Column('immediate_action', sa.Text(), nullable=True),
    sa.Column('bot_script', sa.Text(), nullable=True),
    sa.Column('escalation_target', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('flag_id', name=op.f('pk_kb_red_flags'))
    )
    op.create_table('kb_routing_rules',
    sa.Column('rule_id', sa.String(), nullable=False),
    sa.Column('trigger_condition', sa.Text(), nullable=False),
    sa.Column('route_to', sa.String(), nullable=True),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('trajectory_factor', sa.Text(), nullable=True),
    sa.Column('priority', sa.SmallInteger(), nullable=True),
    sa.CheckConstraint('priority IN (1,2,3) OR priority IS NULL', name=op.f('ck_kb_routing_rules_priority_range')),
    sa.PrimaryKeyConstraint('rule_id', name=op.f('pk_kb_routing_rules'))
    )
    op.create_table('kb_scenarios',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('topic', sa.String(), nullable=False),
    sa.Column('scenario_description', sa.Text(), nullable=True),
    sa.Column('phrase', sa.Text(), nullable=False),
    sa.Column('pending_governance_review', sa.Boolean(), nullable=False),
    sa.Column('phrase_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_scenarios'))
    )
    op.create_table('kb_signals',
    sa.Column('signal_id', sa.String(), nullable=False),
    sa.Column('clinical_concept', sa.Text(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('mh_disorder', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('severity', sa.SmallInteger(), nullable=True),
    sa.Column('red_flag', sa.Boolean(), nullable=False),
    sa.Column('tone_cues', sa.Text(), nullable=True),
    sa.Column('trajectory_cues', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('phrasings_text', sa.Text(), nullable=True),
    sa.Column('phrasing_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('matched_rules', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('severity IN (1,2,3)', name=op.f('ck_kb_signals_severity_range')),
    sa.PrimaryKeyConstraint('signal_id', name=op.f('pk_kb_signals'))
    )
    op.create_table('kb_sufficiency_patterns',
    sa.Column('pattern_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('pattern_name', sa.Text(), nullable=False),
    sa.Column('tier', sa.SmallInteger(), nullable=True),
    sa.Column('is_placeholder', sa.Boolean(), nullable=False),
    sa.Column('minimum_signals_raw', sa.Text(), nullable=True),
    sa.Column('must_have_signals_raw', sa.Text(), nullable=True),
    sa.Column('confidence_rule', sa.Text(), nullable=True),
    sa.Column('tie_breaker_logic', sa.Text(), nullable=True),
    sa.Column('probing_guidance', sa.Text(), nullable=True),
    sa.Column('graceful_exit_trigger', sa.Text(), nullable=True),
    sa.Column('pattern_name_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.CheckConstraint('tier IN (1,2,3) OR tier IS NULL', name=op.f('ck_kb_sufficiency_patterns_tier_range')),
    sa.PrimaryKeyConstraint('pattern_id', name=op.f('pk_kb_sufficiency_patterns'))
    )
    op.create_table('kb_symptoms',
    sa.Column('symptom_id', sa.String(), nullable=False),
    sa.Column('id_family', sa.String(), nullable=False),
    sa.Column('symptom', sa.Text(), nullable=False),
    sa.Column('how_described', sa.Text(), nullable=True),
    sa.Column('how_described_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('likely_root', sa.Text(), nullable=True),
    sa.Column('linked_signal_ids', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('linked_concepts', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('any_linked_red_flag', sa.Boolean(), nullable=False),
    sa.Column('max_linked_severity', sa.SmallInteger(), nullable=True),
    sa.Column('distinguishing_cues', sa.Text(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.CheckConstraint("id_family IN ('PHYS','EM')", name=op.f('ck_kb_symptoms_id_family_valid')),
    sa.PrimaryKeyConstraint('symptom_id', name=op.f('pk_kb_symptoms'))
    )
    op.create_table('kb_tier_question_bank',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bank_source', sa.String(), nullable=False),
    sa.Column('scenario_or_topic', sa.String(), nullable=False),
    sa.Column('subsection', sa.String(), nullable=True),
    sa.Column('question_type', sa.String(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('answer_options_raw', sa.Text(), nullable=True),
    sa.Column('tier_routing', sa.String(), nullable=True),
    sa.Column('question_embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source_file', sa.String(), nullable=False),
    sa.Column('language', sa.String(), nullable=False),
    sa.CheckConstraint("bank_source IN ('questions_by_scenario','career_question_set')", name=op.f('ck_kb_tier_question_bank_bank_source_valid')),
    sa.CheckConstraint("question_type IN ('open','close_ended')", name=op.f('ck_kb_tier_question_bank_question_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_kb_tier_question_bank'))
    )
    op.create_table('kb_versions',
    sa.Column('version_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('label', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('retrieval_hit_rate', sa.Double(), nullable=True),
    sa.Column('grounding_accuracy', sa.Double(), nullable=True),
    sa.Column('tier_routing_accuracy', sa.Double(), nullable=True),
    sa.Column('adversarial_pass_rate', sa.Double(), nullable=True),
    sa.Column('validated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('activated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deactivated_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('building','validating','live','rolled_back','failed')", name=op.f('ck_kb_versions_status_valid')),
    sa.PrimaryKeyConstraint('version_id', name=op.f('pk_kb_versions'))
    )
    op.create_table('prompt_config',
    sa.Column('config_key', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('clinical_signoff_by', sa.String(), nullable=True),
    sa.Column('clinical_signoff_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('config_key', name=op.f('pk_prompt_config'))
    )
    op.create_table('sessions',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('mode', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('lifecycle_state', sa.String(), nullable=False),
    sa.Column('assigned_tier', sa.SmallInteger(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('mood_tag', sa.String(), nullable=True),
    sa.Column('livekit_room_id', sa.String(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('closed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("lifecycle_state IN ('live','closed','tiered','shared')", name=op.f('ck_sessions_lifecycle_state_valid')),
    sa.CheckConstraint("mode IN ('voice','text','avatar') OR mode IS NULL", name=op.f('ck_sessions_mode_valid')),
    sa.CheckConstraint('assigned_tier IN (1,2,3) OR assigned_tier IS NULL', name=op.f('ck_sessions_assigned_tier_range')),
    sa.PrimaryKeyConstraint('session_id', name=op.f('pk_sessions'))
    )
    op.create_table('kb_content_chunks',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('pattern_name', sa.String(), nullable=True),
    sa.Column('tier', sa.SmallInteger(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('embedding', pgvector.sqlalchemy.vector.VECTOR(dim=1024), nullable=True),
    sa.Column('source_document', sa.String(), nullable=True),
    sa.Column('language', sa.String(), nullable=False),
    sa.Column('linked_pattern_id', sa.Integer(), nullable=True),
    sa.CheckConstraint("content_type IN ('probing_guidance','psycho_education','self_care_tool')", name=op.f('ck_kb_content_chunks_content_type_valid')),
    sa.ForeignKeyConstraint(['linked_pattern_id'], ['kb_sufficiency_patterns.pattern_id'], name=op.f('fk_kb_content_chunks_linked_pattern_id_kb_sufficiency_patterns')),
    sa.PrimaryKeyConstraint('chunk_id', name=op.f('pk_kb_content_chunks'))
    )
    op.create_table('turn_audit_log',
    sa.Column('turn_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('turn_number', sa.Integer(), nullable=True),
    sa.Column('served_from', sa.String(), nullable=True),
    sa.Column('retrieved_chunk_ids', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('matched_signal_ids', sa.ARRAY(sa.Text()), nullable=True),
    sa.Column('matched_rule_id', sa.String(), nullable=True),
    sa.Column('triage_tier', sa.SmallInteger(), nullable=True),
    sa.Column('interlock_triggered', sa.Boolean(), nullable=False),
    sa.Column('interlock_flag_id', sa.String(), nullable=True),
    sa.Column('fallback_scenario_id', sa.Integer(), nullable=True),
    sa.Column('latency_ms', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('kb_version_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['fallback_scenario_id'], ['kb_fallback_scenarios.scenario_id'], name=op.f('fk_turn_audit_log_fallback_scenario_id_kb_fallback_scenarios')),
    sa.ForeignKeyConstraint(['kb_version_id'], ['kb_versions.version_id'], name=op.f('fk_turn_audit_log_kb_version_id_kb_versions')),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], name=op.f('fk_turn_audit_log_session_id_sessions')),
    sa.PrimaryKeyConstraint('turn_id', name=op.f('pk_turn_audit_log'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turn_audit_log')
    op.drop_table('kb_content_chunks')
    op.drop_table('sessions')
    op.drop_table('prompt_config')
    op.drop_table('kb_versions')
    op.drop_table('kb_tier_question_bank')
    op.drop_table('kb_symptoms')
    op.drop_table('kb_sufficiency_patterns')
    op.drop_table('kb_signals')
    op.drop_table('kb_scenarios')
    op.drop_table('kb_routing_rules')
    op.drop_table('kb_red_flags')
    op.drop_table('kb_layer_content')
    op.drop_table('kb_guardrail_rules')
    op.drop_table('kb_fallback_scenarios')
    op.drop_table('kb_emotion_phrases')
    op.drop_table('kb_clarification_phrases')
    op.drop_table('kb_career_lookup')
    op.drop_table('kb_anxiety_situations')
    # ### end Alembic commands ###
